name: GitHub Actions Demo

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: GitHub वरून कोड कॉपी करा
        uses: actions/checkout@v4

      - name: प्रोजेक्ट टेस्ट करा
        run: echo "Testing our code... Code is successfully tested!"

      - name: प्रोजेक्ट बिल्ड करा
        run: echo "Building our application... Build Successful!"
